### ISSUE TITLE
Feature request: Spacebar to play/pause regardless of focus

### ISSUE THREAD

**Issue by groenroos** [cpiber/NebulaEnhance#12]
On both YouTube and Nebula, when you first come onto the video page, you can use spacebar to play/pause the video.

However, if you then use any of the player controls with your mouse (theatre mode, settings menu, fullscreen, etc), on Nebula, that particular player control button now retains focus, and pressing spacebar toggles that button now, instead of playback.

On YouTube, as long as the focus is somewhere within the page (and not on a form input), spacebar will always only control play/pause.

I know I can press `K` for more reliable playback control on both platforms, but I think spacebar feels more natural, and clearly YouTube agrees since they've spent the engineering effort to make it so.

**Comment by cpiber** [comment]
Thanks for pointing that out!

Apparently all you need is `capture: true`, then the listener is called even before handling accessibility. That makes this an easy fix!
