### ISSUE TITLE
Filter creators by newly added.

### ISSUE THREAD

**Issue by vUbev** [cpiber/NebulaEnhance#13]
Hey there. First off, I want to thank you for the extension and the features you've been adding. It's a must-have for Nebula in my opinion.

I don't know how realistic this feature request is (probably not much, but idk), but I'd like the ability to [look for creators](https://nebula.app/videos?display=creators) and see who joined recently.

When I got Nebula I skimmed through every channel and it helped me find some great creators to follow. Now, almost a year later, I would like to do the same with the new creators.
I'm sorry if formatting is weird, or my post doesn't conform to github standards. I literally just made the account to post this.

**Comment by ewonais** [comment]
> Since I couldn't find anything, I sent an email to the Nebula help-center, and they informed me that it is currently not possible to sort, but that it is on their list.
> 
> I'll look again at what I can do when they have implemented sorting.

nebula yhas now added that to the website
https://nebula.tv/videos?display=creators
![image](https://github.com/cpiber/NebulaEnhance/assets/86527854/a467b145-3802-4b37-be44-5fb8a8561f38)

**Comment by cpiber** [comment]
Interesting, thanks for sharing, I'll close this then
