### ISSUE TITLE
Feature request: the ability to filter out certain creaters

### ISSUE THREAD

**Issue by Protonull** [cpiber/NebulaEnhance#16]
In a similar fashion to how you can natively follow creators, I think there should be an inverse option to hide certain creators when generally browsing Nebula. It's not really possible to avoid certain creators right now. This feature would only effect the catalogue; it shouldn't prevent you from actually watching their videos.

**Comment by cpiber** [comment]
Do you mean to hide creators from https://nebula.app/videos ?

Also keep in mind that this is an independent browser extension, so the solution probably won't be that pretty. I'd need to save which creators to ignore in the browser and then just hide the video, since there is afaik no way to filter in the API.

**Comment by Protonull** [comment]
> Do you mean to hide creators from https://nebula.app/videos ?

Precisely.

> so the solution probably won't be that pretty

Not necessarily. I've just tested in my browser by deleting a video entry from the catalogue by removing its most-parent div and it doesn't leave a hole as the other videos move to fill in the gaps. Likewise, the infinite scrolling feature still works as expected.

**Comment by cpiber** [comment]
> I've just tested in my browser by deleting a video entry from the catalogue by removing its most-parent div
That's what I would've done as well

> and it doesn't leave a hole as the other videos move to fill in the gaps. Likewise, the infinite scrolling feature still works as expected.
Not what I meant. Nebula fetches as videos such that they go evenly into rows. Just hiding some of the videos will mean that the last row will end unevenly. I also have to integrate the option to block/unblock creators into the UI...

**Comment by Protonull** [comment]
> Just hiding some of the videos will mean that the last row will end unevenly.

That is true. When removing the div, the law row of the catalogue is uneven but the infinite scrolling feature ignores this so the unevenness is always at the bottom of the page.

**Comment by cpiber** [comment]
I have started work on it, please give it a go: 
[enhancer_for_nebula-1.0.09.zip](https://github.com/cpiber/NebulaEnhance/files/8231017/enhancer_for_nebula-1.0.09.zip)

Currently, on the creator page it adds an icon to show and hide a particular creator. I'm planning on adding a list of hidden creators to the options.

**Comment by cpiber** [comment]
I also just noticed that on the homepage, the slider really does not like having elements removed, so I just greyed it out there: 
![image](https://user-images.githubusercontent.com/59023762/157849378-88f3b7e1-4e04-46fc-b2f1-1752b8cb2c07.png)

Again, please tell me what you think.

**Comment by cpiber** [comment]
Updated extension: [enhancer_for_nebula-1.0.09.zip](https://github.com/cpiber/NebulaEnhance/files/8231815/enhancer_for_nebula-1.0.09.zip)

How to install: https://github.com/cpiber/NebulaEnhance/discussions/9#discussioncomment-1334893

**Comment by Protonull** [comment]
> Updated extension: [enhancer_for_nebula-1.0.09.zip](https://github.com/cpiber/NebulaEnhance/files/8231815/enhancer_for_nebula-1.0.09.zip)

Just tested this out and seems to work fine. The video is removed from https://nebula.app/videos and its various categories which is excellent. I do see what you mean about the sliders on https://nebula.app/ though. Since it's unavoidable, perhaps having some text over the thumbnail (or replacing the thumbnail and having it be less greyed out) which explains why it's greyed out, like "This creator is hidden by you."

Another thing is the show/hide buttons. I think they should be flipped. The image should, in my opinion, reflect the *current* state, rather than reflect the future state should you click the button. My first instinct when looking on creator pages is "Wait, I have this creator hidden?" when it's the button to hide the creator.

**Comment by cpiber** [comment]
>  perhaps having some text over the thumbnail 

good idea

> The image should, in my opinion, reflect the current state

These are always a bit tricky ^^ But I guess you're right, that's probably more intuitive

**Comment by cpiber** [comment]
![image](https://user-images.githubusercontent.com/59023762/157899233-2f72f0b4-9168-4939-a339-d1149b1a0d8a.png)
I hope it doesn't stand out too much, what do you think?

**Comment by Protonull** [comment]
Looks good 👍

**Comment by cpiber** [comment]
The extension is updated on both stores now :)
