### ISSUE TITLE
Auto open nebula links from youtube

### ISSUE THREAD

**Issue by Rihcus** [cpiber/NebulaEnhance#18]
Hi saw a feature in your extension that adds a watch in nebula button in youtube. Is it possible to ad a feature to auto open nebula open clicking a compatible nebula creators video. Best example is the watch in odessy extension.

https://github.com/kodxana/Watch-on-Odysee

**Comment by cpiber** [comment]
That should be possible. Could you please describe how it behaves? Does it just open a new tab if it's found one? Replacing the current tab seems possible but not very user-friendly...

**Comment by dereineLauch** [comment]
I would pause the YouTube video and then open the nebula link in a new tab.

**Comment by dereineLauch** [comment]
And if you are on Nebula and then open the associated YouTube video, it should not open the Nebula video again.

**Comment by cpiber** [comment]
[enhancer_for_nebula-1.0.9.zip](https://github.com/cpiber/NebulaEnhance/files/8311946/enhancer_for_nebula-1.0.9.zip)
Here is the feature implemented @Rihcus. Could you please check that it works as intended? How to install: https://github.com/cpiber/NebulaEnhance/discussions/9#discussioncomment-1334893

**Comment by Rihcus** [comment]
> [enhancer_for_nebula-1.0.9.zip](https://github.com/cpiber/NebulaEnhance/files/8311946/enhancer_for_nebula-1.0.9.zip) Here is the feature implemented @Rihcus. Could you please check that it works as intended? How to install: [#9 (reply in thread)](https://github.com/cpiber/NebulaEnhance/discussions/9#discussioncomment-1334893)

Ran a few tests and it mostly works (no issues with auto launch):

Tested links that work:
https://www.youtube.com/watch?v=ysBFb3bcriI&t=105s 
https://www.youtube.com/watch?v=KJsWaJVtZWA&t=1s
https://www.youtube.com/watch?v=mXpwgg5TxOU

The only channel I'm having issues with is cold fusion, the extension is unable to find youtube to nebula links (but its able to find youtube links in nebula with 35% accuracy):

https://www.youtube.com/watch?v=W5P8ZBLC450
https://nebula.app/videos/coldfusion-spinal-implant-makes-completely-paralyzed-walk-again

https://www.youtube.com/watch?v=D2vLH0tJVHo&t=3s
https://nebula.app/videos/coldfusion-russian-sanctions-and-unintended-consequences

**Comment by cpiber** [comment]
> no issues with auto launch

nice, then I'll push that on the next update

> The only channel I'm having issues with is cold fusion

Thanks for pointing that out, I just investigated, and it looks like standard didn't actually add the nebula link to their page: https://standard.tv/creators/. All other creators have a link to the nebula channel, but ColdFusion only has a YouTube link.

This as coincidentally led me to find that these links aren't all that accurate, e.g. for Rare Earth they only point to the [rare-earth-originals](https://nebula.app/rare-earth-originals) channel and not their main channel [rareearth](https://nebula.app/rareearth) . I guess I'll add an approximation there as well.
