### ISSUE TITLE
RSS-Feed link

### ISSUE THREAD

**Issue by dereineLauch** [cpiber/NebulaEnhance#19]
A Reddit user [created a tool](https://www.reddit.com/r/watchnebula/comments/nt0ksv/nebula_rss_feed/) to get the RSS-Feed link from any Nebula channel.
Maybe you could implement this the same way Nebula do this with Podcasts.

How nebula do this with Podcasts: 
![image](https://user-images.githubusercontent.com/84781281/159174761-e3fd06f8-7223-4792-a41f-ffc8561ddbc2.png)

How I would implement it on normal channels: 
![image](https://user-images.githubusercontent.com/84781281/159174680-5719ac79-4354-47c2-aa25-5b6b98a58b4b.png)

**Comment by cpiber** [comment]
To add a link to that site should be possible, yes
I'm not sure yet how good of an idea it is to include external sites though... Maybe with a warning

**Comment by cpiber** [comment]
[enhancer_for_nebula-1.0.9.zip](https://github.com/cpiber/NebulaEnhance/files/8312075/enhancer_for_nebula-1.0.9.zip) Here as well, should be done

**Comment by cpiber** [comment]
@dereineLauch if that version works fine for you, I'd release it as an official version

**Comment by cpiber** [comment]
Interesting, the "hide creator" button is also not placed correctly, that shouldn't happen. Have you tried reloading the page after activating the extension?

**Comment by cpiber** [comment]
Seems to be a css specifity issue with chrome...

**Comment by dereineLauch** [comment]
> Seems to be a css specifity issue with chrome...

Yes. I normally use chrome. But tried it now with Firefox, and it worked correctly.

**Comment by cpiber** [comment]
[enhancer_for_nebula-1.0.9.zip](https://github.com/cpiber/NebulaEnhance/files/8315391/enhancer_for_nebula-1.0.9.zip) Please try this version

**Comment by dereineLauch** [comment]
Works fine. Always appreciate your work
