### ISSUE TITLE
Please don't redirect me to your changelog each time I update on Firefox

### ISSUE THREAD

**Issue by twizmwazin** [cpiber/NebulaEnhance#2]
This has happened multiple times now. It is fine to open the changelog in a background tab so I can see it when I'm ready, but this has interrupted work meetings and gaming sessions and is unnecessary.

**Comment by cpiber** [comment]
Browsers don't allow opening tabs in the background (because ad pages did that).
If you don't like it please disable showing changelogs.

**Comment by twizmwazin** [comment]
Do you know where I might find that option? I've not had to do this with other Firefox addons and a quick google is not helping me, but perhaps I am searching for the wrong thing.

**Comment by cpiber** [comment]
It is something I have added. There is a checkbox at the bottom of the options page.
![image](https://user-images.githubusercontent.com/59023762/124028796-b2cda000-d9f4-11eb-89a6-9f972457a05a.png)
You can untick this box and it should stop

**Comment by twizmwazin** [comment]
Thank you!

**Comment by cpiber** [comment]
Update: I have now noticed that an extension has indeed the permissions to open a tab in the background (as opposed to a normal website). This requires that the options are opened in a completely separate tab (not in the box as they are now), which I plan to do for the next big update.
