### ISSUE TITLE
Skip Subtitle Menu if only one track available

### ISSUE THREAD

**Issue by dereineLauch** [cpiber/NebulaEnhance#21]
Currently there is an additional menu when you want to activate subtitles. 
I just want to click on the "Subtitles" button and then the subtitles are activated, because there are always only English subtitles anyway and therefore this extra menu is unnecessary.
![image](https://user-images.githubusercontent.com/84781281/160641717-81c933d5-2071-4fa4-95d2-5969a633a2e6.png)

**Comment by cpiber** [comment]
could you provide me with a link to that, please, so I can test?

**Comment by dereineLauch** [comment]
What Link? I would appreciate if you implement my proposal and implement it in your extension.

**Comment by dereineLauch** [comment]
Ah, sorry for the misunderstanding.

**Comment by dereineLauch** [comment]
I'll try it this afternoon. Thank you in advance.

**Comment by dereineLauch** [comment]
Ok, finally tried it. Turning the subtitles on works fine, but when I want to turn it off again, the menu opens, and I have to make two clicks.

**Comment by dereineLauch** [comment]
> Not entirely happy with the option name/title, do you have any suggestions on that?

Maybe just how you named this GitHub issue, so "Skip Subtitle Menu if only one track available". But I don't know how it's named currently because my extension is German.

**Comment by cpiber** [comment]
> Ok, finally tried it. Turning the subtitles on works fine, but when I want to turn it off again, the menu opens, and I have to make two clicks.

I made it so skipping it would only apply if it not already activated, but you are right, it would make more sense to automatically deactivate it.

> But I don't know how it's named currently because my extension is German.

"Use first subtitle", similar to the German title. I think the issue title is too long, all options titles are very short... But I've added a hint so it should be fine.

**Comment by dereineLauch** [comment]
Ok, nice.
