### ISSUE TITLE
Load Nebula link and Auto Open Nebula Link from youtube no longer works (FireFox/Chrome)

### ISSUE THREAD

**Issue by Rihcus** [cpiber/NebulaEnhance#23]
Chrome
![image](https://user-images.githubusercontent.com/30292597/171406423-a03ea550-fe22-49de-9fde-5333e11cd133.png)
![image](https://user-images.githubusercontent.com/30292597/171406952-dd5017e8-f8c0-4bef-841a-d621ede9b90d.png)

Firefox
![image](https://user-images.githubusercontent.com/30292597/171406601-f94774e1-7e84-48b7-85af-b565116cd4b9.png)
![image](https://user-images.githubusercontent.com/30292597/171406909-167dbcff-e539-487f-bab4-ebf2f93ff66a.png)

Nebula Enhancer Settings:
![image](https://user-images.githubusercontent.com/30292597/171406712-7ebe458a-9126-4a64-9921-de0c43565234.png)

Tested video:

YT
https://youtu.be/UA6UythLlEI

Nebula
https://nebula.app/videos/hai-how-stenographers-type-at-300-words-per-minute

**Comment by cpiber** [comment]
Thank you for reporting. I will look at it, but currently I have a bit going on with Uni so I can't promise a fast fix

**Comment by cpiber** [comment]
Youtube have completely changed their event system, so the extension didn't pick up on the navigation anymore. Should be fixed now. I'll release the new version tomorrow.
