### ISSUE TITLE
Exact release date of a video 

### ISSUE THREAD

**Issue by dereineLauch** [cpiber/NebulaEnhance#25]
Currently, you can't see the exact release date of a video, but only an indication like: "14 hours ago".
But I prefer to have the exact release date.
So, could you add the function that when you hover the mouse over the "14 hours ago" it shows the exact date and time?
Or that it looks like this: "2022-06-11 17:40:33 (14 hours ago)". I don't care how it is formatted and implemented, but I want to be able to see the publication date.

I don't know if this is technically possible, but it would be cool if you can also see the release date of a channel. I know that you can see the release date in the [new channel rss-feed](https://rss.nebula.app/video/channels.rss), but there you only see the last 30 channels or so.

Do not forget a setting for time zones.

Thank you, in advance.

**Comment by cpiber** [comment]
I assume you mean on the video page? Or also in the video list?

Nebula already saves this information in the dom:
![image](https://user-images.githubusercontent.com/59023762/173228960-74f0120f-baea-464a-a7f9-72617e7f9077.png)

So yes, completely doable. The browser automatically converts the dates to the user's timezone, so nothing special to consider. I'll include it in the next release.

**Comment by cpiber** [comment]
What do you think?

![image](https://user-images.githubusercontent.com/59023762/173234833-4adbf2a1-45ac-45b7-a237-a869f42c1841.png)
![image](https://user-images.githubusercontent.com/59023762/173234806-37610762-7499-4489-bbd5-ee8dc1f85e17.png)

Also works in video lists
![image](https://user-images.githubusercontent.com/59023762/173234877-ca60cb6f-bc46-4288-978e-eb5d5afd40e7.png)
![image](https://user-images.githubusercontent.com/59023762/173234890-bec1c7bd-f9eb-424a-877d-179af82fc44a.png)

**Comment by dereineLauch** [comment]
Yes, exactly what I wanted - in the video list and in the video itself. 
I've also seen that you can see the exact release date.

Thanks.

**Comment by dereineLauch** [comment]
> it would be cool if you can also see the release date of a channel

What about that. It's not nearly as important, but it would still be cool.

**Comment by cpiber** [comment]
> > it would be cool if you can also see the release date of a channel
> 
> What about that. It's not nearly as important, but it would still be cool.

Sorry, overlooked that. What exactly do you mean? When a video was last released? Or when a video was first released?

**Comment by dereineLauch** [comment]
Sorry for the bad explanation.
I want to know how long the channel has been on Nebula.
There is this rss feed with all new channels on Nebula and the date the channel was added to Nebula: https://rss.nebula.app/video/channels.rss
And I want to see this date on the channel page on Nebula.

The Problem is that the RSS feed only shows the last 30 Channels, but maybe you can find the date in the dom.

Sorry for the bad explanation, do you understand it now?

**Comment by cpiber** [comment]
That date isn't when the channel was added to nebula, it's the date of their last upload, see f.e. https://nebula.app/nothingbuttech/, third in the list, but their oldest video is 9 months old

**Comment by dereineLauch** [comment]
Ok, no problem.

**Comment by cpiber** [comment]
Published in version 1.1.0, should be out on the stores in a few hours
