### ISSUE TITLE
Feature Request:  Pause youtube auto play when auto opening nebula

### ISSUE THREAD

**Issue by Rihcus** [cpiber/NebulaEnhance#27]
I noticed on chrome when using the automatically open nebula link the original youtube video plays in the background requiring going back to the tab pausing then watching on the nebula. I know there are options to disable youtube auto play but I was wondering if it was possible to block youtube auto-play just on nebula yt videos.

**Comment by cpiber** [comment]
Actually the extension pauses the video already and it seems to work on Firefox and last I tested with Chromium... I'll have to investigate this
