### ISSUE TITLE
Show video immediately full-screen

### ISSUE THREAD

**Issue by dereineLauch** [cpiber/NebulaEnhance#30]
I would like that when clicking on a video, the full Screen mode is immediately activated. Most of the time I click directly on full screen anyway.

**Comment by cpiber** [comment]
Unfortunately browsers don't allow this, similar to autoplay. The user needs to interact with the page before such an action can be taken.

You can try it out yourself with this custom script:
```js
document.addEventListener('enebula-load-video', () =>
	document.querySelector('video').requestFullscreen().catch(err => alert(`Error requesting fullscreen: ${err}`))
)
```
You should see an error alert.
