### ISSUE TITLE
Copy text from subtitles

### ISSUE THREAD

**Issue by dereineLauch** [cpiber/NebulaEnhance#31]
It would be great if it is possible to copy text from the subtitles. Currently, you can copy everything from the website except the subtitle-text. It would be a great feature when you want to research further about a topic.
Thanks in advance.

**Comment by cpiber** [comment]
Interesting idea. I'm not sure if I can get that easily, but it should be available somewhere. How do you imagine this feature to work? Do you just want to be able to select the text over the video?

**Comment by dereineLauch** [comment]
Yeah, I would like to copy it like you copy the title of the video.

**Comment by cpiber** [comment]
Turns out the fix is pretty easy, since they simply disable clicking for the tracks via CSS. I'm not sure when/if I'll integrate it directly, but for now you can use the following custom script:

```js
document.head.innerHTML+="<style>.vjs-text-track-cue{pointer-events:all}</style>"
```

This adds a style that re-enables pointer events for subtitles. Note that this means play/pause will not work when clicking the subtitles, you need to click the video directly.

**Comment by dereineLauch** [comment]
Thanks. The copying works now, but the whole website is a bit destroyed. Maybe again a chrome thing.
![image](https://user-images.githubusercontent.com/84781281/186195934-5bba3f42-e8d9-4d04-9ad8-66472fb8d430.png)
![image](https://user-images.githubusercontent.com/84781281/186195956-f3d44f68-b99b-4c64-bb19-cb2cb4e03fca.png)

**Comment by cpiber** [comment]
Yeah, for some reason chrome doesn't appear to load stylesheets with this... It works with this slightly more complicated one:

```js
document.onload=()=>{document.head.innerHTML+="<style>.vjs-text-track-cue{pointer-events:all}</style>"}
```
It's basically the same, but waits for the site to load before applying the style

**Comment by dereineLauch** [comment]
Nice! Thanks. Works perfectly.

**Comment by cpiber** [comment]
Just pushed a new version that has this functionality, should be out in a few hours.

There shouldn't be any conflict if you leave the custom script, but I would recommend removing it.

**Comment by dereineLauch** [comment]
Thanks. Thats nice.

**Comment by cpiber** [comment]
New update: Unfortunately with the new player, the handling of subtitles changed to native html text tracks, which do not support these options. As it would be too difficult (and introduce too many changes to Nebula) to re-implement old subtitle handling, this feature will be removed from the next version.
