### ISSUE TITLE
Add 'beta.' when clicked on a 'nebula.tv' link

### ISSUE THREAD

**Issue by dereineLauch** [cpiber/NebulaEnhance#32]
I always watch on 'beta.nebula.tv', but when I click on a 'nebula.tv' link, I'm not on the beta side. It's not that bad, but it through would be nice to have an option that puts 'beta.' in front of each 'neubula.tv'. 
Maybe you could that.

**Comment by cpiber** [comment]
So you mean to add an option that always redirects you to the beta site when you click a link? Should be easy, and you can do that with a custom script:

```js
window.onload=()=>{if(location.host!="beta.nebula.tv"){const u=new URL(location.href);u.host="beta.nebula.tv";location.href=u.toString()}}
```

**Comment by dereineLauch** [comment]
Nice, that works, thanks!!!
