### ISSUE TITLE
Nebula link doesn't load from Youtube

### ISSUE THREAD

**Issue by aronkvh** [cpiber/NebulaEnhance#36]
The youtube link shows in Nebula, but not the other way around.
```
Firefox 107.0 (64-bit) X11, Linux (KDE Neon 22.04 jammy)
NebulaEnhance 1.2.0
```

**Comment by cpiber** [comment]
So... YouTube recently launched quite a big update (channel names changed etc), it seems that broke stuff for me. It's not a Firefox-specific issue, I will investigate this and how to fix it.

**Comment by cpiber** [comment]
The problem was less than I thought, it was simply the channel URL that was changed, which meant I didn't find the symbol. That is fixed now, and even the button design updated to the new style. I'll probably push the new update tomorrow.
