### ISSUE TITLE
Direct video / download links

### ISSUE THREAD

**Issue by matejdro** [cpiber/NebulaEnhance#41]
Occasionally I want to download a video from Nebula to watch it offline later. My current process is using VideoDownloadHelper to find a direct link to the video stream that can be then saved using VLC.

However, especially the first part of this process is cumbersome. It would be nice if extension would provide a direct link to the video stream that can be saved with VLC or similar program.

I would be up for creating a PR for this, if accepted.

**Comment by cpiber** [comment]
VDH is literally a downloader, why go via VLC?

Did you look into getting this link? Because it's not easy. Without decoding the HLS separately, I don't think there's a good way, since the Nebula player uses HLS. But if you have a solution, please do a PR.

**Comment by matejdro** [comment]
> VDH is literally a downloader, why go via VLC?

I'm only using the extension. Kinda put off by installing extra software on my PC.

> Did you look into getting this link? 

Huh, this seemed much easier in the Zype days, but now it seems way more complicated. Will take a look at it at some point.

**Comment by cpiber** [comment]
> I'm only using the extension. Kinda put off by installing extra software on my PC.

The extension can usually handle downloads, though I haven't tried it in this instance. But isn't VLC extra software as well?

> Will take a look at it at some point.

Good luck, I look forward to it :)

**Comment by matejdro** [comment]
I've looked into it for a while and gave up. I could get the playlist links, but video and audio were in the separate files, so this method would be a lot of hassle.

Instead, I've discovered that https://github.com/yt-dlp/yt-dlp seems to support Nebula, so I will likely use this.

**Comment by cpiber** [comment]
`yt-dlp` is a nice project :)

Could you please share your methods of finding the playlists? Maybe this could help with #39, since I'm a bit stuck with that feature as well
