### ISSUE TITLE
Library appears empty when using "Hide watched videos"

### ISSUE THREAD

**Issue by wolleydev** [cpiber/NebulaEnhance#42]
Hi, and thanks for making this lifesaving extension.

With the "Hide watched videos" option enabled, there is this issue that will show my library as empty if there is no recent unwatched video.
It was working fine earlier when I still had at least the latest video as unwatched. Most recent video would show and then it would dynamically load further and further the unwatched videos. However, now that I have watched it, my library doesn't show any video and instead shows the following message: "You aren't following any creators yet. Check out some featured creators and follow them!", which is of course untrue.
I am no developper, but my guess is that the infinite scroll doens't get triggered because at least one video has to be loaded for this.

**Comment by cpiber** [comment]
That is very possible. I don't use the library feature much so I haven't noticed this, I'll look into it

**Comment by cpiber** [comment]
I have implemented a fix, please download this version to try it out: 
[enhancer_for_nebula-1.3.1.1.zip](https://github.com/cpiber/NebulaEnhance/files/11242639/enhancer_for_nebula-1.3.1.1.zip)

To install:
- in Chrome, please go to Setting, click Extensions (lower left), enable Developer Mode (upper right) and select "Load unpacked". Here select the unzipped folder (should contain folders _locale, icons, scripts, styles).
- in Firefox, please go to about:addons, click on the gear (top right), select Debug addons and click "Load Temporary Addon". Here select the zip you downloaded.

**Comment by wolleydev** [comment]
It seems to be working! I was able to load older videos without the error message.
