### ISSUE TITLE
Feature Request:  Hide old and/or long videos

### ISSUE THREAD

**Issue by ewonais** [cpiber/NebulaEnhance#46]
For news channels like tldr and The Friday Checkout, hide videos oloder than X
Old news is not intresting to watch so it ends upp clogging my libery

**Comment by cpiber** [comment]
So just hide videos that are older than a certain setting? Or do you think it would make sense to have this setting per-channel?

**Comment by ewonais** [comment]
setting per channel. most chanels usually makes videos that ar not time dependent

**Comment by cpiber** [comment]
The changes you requested should work on, please try it out with this: 
[enhancer_for_nebula-1.3.3.1.zip](https://github.com/cpiber/NebulaEnhance/files/11597599/enhancer_for_nebula-1.3.3.1.zip)

To install:
- in Chrome, please go to Setting, click Extensions (lower left), enable Developer Mode (upper right) and select "Load unpacked". Here select the unzipped folder (should contain folders _locale, icons, scripts, styles).
- in Firefox, please go to about:addons, click on the gear (top right), select Debug addons and click "Load Temporary Addon". Here select the zip you downloaded.

**Comment by ewonais** [comment]
works but i cant find a list of channels i hawe hidden older videos from
"Manage hidden creators" only show completly hidden channels

**Comment by cpiber** [comment]
That's true, maybe I'll change it to just open the settings modal

**Comment by cpiber** [comment]
[enhancer_for_nebula-1.3.3.2.zip](https://github.com/cpiber/NebulaEnhance/files/11599267/enhancer_for_nebula-1.3.3.2.zip)
Here is a version with extended settings from the options screen, please try it out

**Comment by ewonais** [comment]
can it show the blocklimit without neading to lock thr gere? like alll/7d/14d
![image](https://github.com/cpiber/NebulaEnhance/assets/86527854/f1f0ebe3-2dfb-410f-9a66-73467649feb6)

**Comment by cpiber** [comment]
![image](https://github.com/cpiber/NebulaEnhance/assets/59023762/ed44f5f5-5fed-4824-8cf6-96bd94cdc8b6)
something like this?

**Comment by cpiber** [comment]
So based on the duration of the video? Sure

**Comment by cpiber** [comment]
[enhancer_for_nebula-1.3.3.3.zip](https://github.com/cpiber/NebulaEnhance/files/11604754/enhancer_for_nebula-1.3.3.3.zip)
Please try this version, you can now also set the maximum length of the video

**Comment by ewonais** [comment]
works but when hiding old and long videos from the same channel it only shows that  i hide old
![image](https://github.com/cpiber/NebulaEnhance/assets/86527854/588c86bd-b7e0-4325-b4cc-24161c693d82)

**Comment by ewonais** [comment]
3 options
all
age
lenght

if all is hidden the other settings dossent matter. 4 text combinatiopns:
hide all
hide after: x
hide longer than: y
hide after: x or longer than: y

**Comment by cpiber** [comment]
The difficulty isn't in the options, it's how to do it while still supporting localization, since I also translate the extension into german :wink: 

![image](https://github.com/cpiber/NebulaEnhance/assets/59023762/4be6b531-933a-458d-a0a8-058bb9efa09a)
