### ISSUE TITLE
Feature Request: hide nebula+ for some chanels

### ISSUE THREAD

**Issue by ewonais** [cpiber/NebulaEnhance#47]
some channels uplodes alot of unintresting nebula+
for exampel: tour and extended interjuves

**Comment by cpiber** [comment]
Seems feasible, I'll look into it

**Comment by cpiber** [comment]
Please try it out: 
[enhancer_for_nebula-1.3.4.1.zip](https://github.com/cpiber/NebulaEnhance/files/11802077/enhancer_for_nebula-1.3.4.1.zip)

To install:
- in Chrome, please go to Setting, click Extensions (lower left), enable Developer Mode (upper right) and select "Load unpacked". Here select the unzipped folder (should contain folders _locale, icons, scripts, styles).
- in Firefox, please go to about:addons, click on the gear (top right), select Debug addons and click "Load Temporary Addon". Here select the zip you downloaded.

**Comment by ewonais** [comment]
works abd sho0ws up corectly
![image](https://github.com/cpiber/NebulaEnhance/assets/86527854/37e90d92-46ec-46d3-a5e1-a693641f9775)
![image](https://github.com/cpiber/NebulaEnhance/assets/86527854/fa5237cb-8933-446c-8d0c-e274eb379710)
for consistensy, use the same neme in both. use the settingggsname from "Manage hidden creators"

when i removed hide+ it still shows up
![image](https://github.com/cpiber/NebulaEnhance/assets/86527854/ad227481-419e-4d9d-a101-e43045cd244d)
not blocking anything but locks wered

**Comment by cpiber** [comment]
>  for consistensy, use the same neme in both. use the settingggsname from "Manage hidden creators"

Not sure what you're trying to say here.

> when i removed hide+ it still shows up

There was a bug where the setting wasn't properly removed, should work properly in the released version.
