### ISSUE TITLE
Persistent Playlist

### ISSUE THREAD

**Issue by jangrewe** [cpiber/NebulaEnhance#5]
Hi, thanks for your extension, this makes the Nebula site at least a little bit more usable...

I make heavy use of the playlist feature, adding all videos from a creator and watching them in reverse order, but unfortunately the "watch later" list is not persisted across sessions, which then requires me to assemble the list again if there are too many videos to watch in one session.

Could you maybe persist the playlist data to e.g. a cookie or local storage? Thanks!

**Comment by cpiber** [comment]
Hi!

Cookies aren't a great place to store, but I think localStorage should work.I think only saving the latest should be enough.

Until then you can click the share button (upper right of the queue), open that url and bookmark it (or leave the tab open), that remembers the elements and position ;)

**Comment by jangrewe** [comment]
Thank you! :-)
