### ISSUE TITLE
auto redirect to nebula dossent work

### ISSUE THREAD

**Issue by ewonais** [cpiber/NebulaEnhance#51]
![image](https://github.com/cpiber/NebulaEnhance/assets/86527854/2e867545-c98c-46de-9d7f-1303dc8133ea)
![image](https://github.com/cpiber/NebulaEnhance/assets/86527854/56797738-9a5b-43fb-9fbf-483612da6bd9)
button is shown and works but not automaticly

**Comment by cpiber** [comment]
It seems to work when you navigate to it on the page, but not when opened in a new tab, I'll check it.

**Comment by cpiber** [comment]
@ewonais The thing I noticed wasn't actually bug but rather a feature of the options I had enabled (if you navigate back from a Nebula video, it won't try to reopen it). So I can't reproduce this, if this still happens to you, can you please upload some logs here? Open the Developer Tools and navigate to the Console, and enable "verbose mode" (Chrome) / "debug" (Firefox). Only the messages from `content_script.js` are relevant, so you can remove other messages for privacy reasons.

**Comment by ewonais** [comment]
Found it! The problem was a userscript i had.
![image](https://github.com/cpiber/NebulaEnhance/assets/86527854/6e9e4ca1-917f-4c94-8512-aa7f1d7b6289)

**Comment by cpiber** [comment]
Interesting, thanks for checking
