### ISSUE TITLE
Display a visual when changing speed through keyboard

### ISSUE THREAD

**Issue by SudoWatson** [cpiber/NebulaEnhance#52]
I use CTRL + . and CTRL + , to increase and decrease the speed of a video. On YouTube, it nicely shows a nice indicator so I know the speed is changing. On Nebula, this doesn't happen. Which leads me to thinking the video is faster, but not entirely sure, and I don't remember how much it changes by, so I don't know what the multiplier is at. It would be nice to have a little visual indicator to tell me my new speed if I speed the video up or slow it down.

**Comment by cpiber** [comment]
Shouldn't be too hard to implement, might take me a while though due to personal stuff
