### ISSUE TITLE
Feature Request: inport/export settings

### ISSUE THREAD

**Issue by ewonais** [cpiber/NebulaEnhance#56]
This will make switching browsers mutch easier. I switched today ant it took alot of time to manualy mowe my settings.

**Comment by cpiber** [comment]
Makes sense, I'll definitely add that

**Comment by cpiber** [comment]
Please try this version: It has basic import/export functionality. As noted in the popup, there is no check against invalid configuration, so if you try to upload just anything, you might break it. [enhancer_for_nebula-1.3.8.1.zip](https://github.com/cpiber/NebulaEnhance/files/13773580/enhancer_for_nebula-1.3.8.1.zip)

**Comment by ewonais** [comment]
tested and it works.
