### ISSUE TITLE
Addon for Firefox also possible

### ISSUE THREAD

**Issue by Guardian1987** [cpiber/NebulaEnhance#57]
Would it be possible to provide this addon for Firefox as well? I don't want to support Google so I'm using Firefox and would not really like to switch just for one add-on. I understand of course if you don't want to provide this, but it doesn't hurt to ask.

**Comment by cpiber** [comment]
What do you mean? The addon is available in both stores, and even for Firefox for Android. I primarily use Firefox as well.

**Comment by Guardian1987** [comment]
Oh, I was an idiot. I only found themes but of course the addon is available. Sorry for that!
