### ISSUE TITLE
YouTube->Nebula link on mobile does not work

### ISSUE THREAD

**Issue by regolithian** [cpiber/NebulaEnhance#60]
Hi, I have just tried this extension for the first time (awesome idea btw!). Unfortunately I can't seem to get it to work at all on the YouTube side, although it can display a link on a nebula page to YouTube. I am using the latest version 1.3.10 with Firefox on android, I've tried re-adding the add-on, restarting my phone, purging the cashe and every combination of enable options in the settings. I've also tried removing all other add-ons and trying videos of various ages from various creators that I know have uploaded the same video to nebula but  nothing seems to be working. 
Thanks for your time and effort in building this tool! Happy to help with any more detail if you need it. 😊

**Comment by cpiber** [comment]
I haven't used the YouTube side personally in a long time, there's a good chance it's broken, since YouTube changes things every so often. I'll look into it when I have time

**Comment by cpiber** [comment]
Main problem here was just that I hadn't implemented the feature for YouTube mobile. youtube.com and m.youtube.com are different enough that I need to have two different versions for the video detection. But doing this I could also improve the desktop code somewhat.

Next version should work properly.

**Comment by regolithian** [comment]
Wow quick fix, amazing 😍 thankyou!
