### ISSUE TITLE
Feature suggestion: Custom Speeds

### ISSUE THREAD

**Issue by renandr** [cpiber/NebulaEnhance#63]
Adding custom speeds, like in this extension for YouTube:
https://chromewebstore.google.com/detail/youtube-custom-speed/kmfcinojnfabkpndlgomnfjllgeppegb

1.0x to 1.25x it too big of a jump, being able to set up something like 0.8-0.9-1.1-1.2 is great

**Comment by cpiber** [comment]
My extension includes a speed dial, which can set any speed you'd like, in any step size. Would adding entries to the existing menu be better? I'd have to investigate how doable that is...

**Comment by renandr** [comment]
oh sorry, I hadn't seen that

**Comment by cpiber** [comment]
perfect, thanks :)
