### ISSUE TITLE
Allow scroll and move header with expanded/window player

### ISSUE THREAD

**Issue by nicovert** [cpiber/NebulaEnhance#64]
This was mentioned as a possible future change in #48 so I thought I'd offer what I think is an improvement. I have tested it, and use a similar change with youtube, but of course it's just my take on it.

content.scss
```
html.enhancer-fullVideo {
    #video-player {
        height: 100vh !important;
        width: 100vw !important;
        max-height: 100vh !important;
        min-height: 100vh !important;
        max-width: 100vw !important;
        min-width: 100vw !important;
    }

    #NebulaApp > div:first-of-type {
        position: absolute !important;
        top: 100vh !important;
    }

    #NebulaApp > div:last-child {
        margin-top: 0px !important;
    }

    [aria-label="video description"] {
        margin-top: 72px;
    }
}
```

This has the player fill the screen while maintaining the rest of the page, with the exception of the header which gets moved to below the video/above the description.
Though with modifying the header, this can have issues persisting onto other non-video pages, so it should probably only be active on /videos urls, or if the video-player element is present or something.

**Comment by cpiber** [comment]
That might be nice, I'll look into it
