### ISSUE TITLE
Bring back Video-Linking for MV3

### ISSUE THREAD

**Issue by cpiber** [cpiber/NebulaEnhance#65]
In MV2, the extension supports finding the YouTube video for a Nebula video and vice-versa.

- YouTube to Nebula: Transform all `injectFunction*` to bundled files and put into `web_accessible_resources`, the content policy disallows injecting arbitrary code
- Nebula to YouTube: Use offscreen API instead of DOMParser (stashed implementation exists), figure out why sending a response from background script doesn't work

**Comment by SudoWatson** [comment]
Is this expected to be solved soon or is there a way I can downgrade my version? This video linking is the whole reason I have this extension and I'd hate to lose it until a fix is eventually found if it's going to take a while

**Comment by cpiber** [comment]
Depends on how much time I have.
If you are on firefox, everything works. Unfortunately, Chromium forces manifest V3 starting now, so not really, though I don't know what their policy is on manually installing MV2 (you can try to install the zip from the releases page, make sure to *not* take the v3 version).

**Comment by cpiber** [comment]
This is now fixed and published, though it may take a while for Google to approve it, especially since this requires a new permission, please check for v1.5.2
