### ISSUE TITLE
`Expand to window size` in Brave

### ISSUE THREAD

**Issue by J-Kappes** [cpiber/NebulaEnhance#66]
Activating `Expand player to window size` moved the sticky banner from the top of the page to the bottom of the player covering up part of the image as well as all the controls.

I had to enter fullscreen in order to deactivate it.

Bug **not** present on same machine using Librewolf.

#### System Information:

- NebulaEnhance: v1.5.0
- Brave Browser: v1.68.137
- OS: Windows 10
- Resolution: 1920 x 1080 at 150% scaling.

**Comment by cpiber** [comment]
Interesting, I'm not using Brave. Can you post a screenshot of what happens? Does it happen consistently?

**Comment by J-Kappes** [comment]
It happened consistently at least 5 times. I'll try to post one when I can.

**Comment by J-Kappes** [comment]
This is a "web app" installed via Brave, but the web view is the same in the regular Browser too.

<img width="960" alt="Capture" src="https://github.com/user-attachments/assets/70bbfbea-40bf-4dd2-992d-a82a252f3bd7">

**Comment by cpiber** [comment]
Sorry, forgot about this one

It's not technically a brave issue, it's just that brave blocks the cookie consent banner by default, which I haven't considered, it's a trivial fix
