### ISSUE TITLE
Changelog isn't relative to installed version

### ISSUE THREAD

**Issue by J-Kappes** [cpiber/NebulaEnhance#67]
Thanks for the quick fix of #66.

For a minute, though, I thought the fix didn't work because the issue persisted while the changelog I opened from the settings said it had been fixed. Turns out I was still on 1.5.0

**Comment by cpiber** [comment]
The changelog shows all released versions, and marks the installed version with "Your Version". I guess this could be done a bit more prominently, I'll see how I do that

**Comment by J-Kappes** [comment]
Oh, didn't see that. 😅 

Maybe a version number close to the changelog button would be warranted.

**Comment by cpiber** [comment]
I've pushed a fix for that, see screenshot below, but I won't release a new version just for that :) so will be included in the next update

![20240817_18h07m23s_grim](https://github.com/user-attachments/assets/cd196dc5-1738-4eda-8920-5ae37f5aca84)
