### ISSUE TITLE
"Add to Watch Later" button is broken by the "Add to playlist" option

### ISSUE THREAD

**Issue by jimcullenaus** [cpiber/NebulaEnhance#68]
When not using Enhancer, the top right of a video's thumbnail is an "Add to Watch Later" button:

![image](https://github.com/user-attachments/assets/7836d306-a628-4db7-84e5-f9b0a37ea888)

When using Enhancer, this at first displays as expected:

![image](https://github.com/user-attachments/assets/6bd3da25-1140-440e-9c7e-c635d2146e5d)

But when you try to actually interact with that option, it changes to "Add to queue", the Enhancer feature:

![image](https://github.com/user-attachments/assets/f0896c19-daeb-447e-aa49-715c662e7f1d)

Desired behaviour would be to be able to use *either* option, such as by putting the "Add to queue" button to the left of the default "Add to Watch Later" button.

**Comment by cpiber** [comment]
Originally, the button should have been moved down, this is a bug after some change by them

**Comment by cpiber** [comment]
Actually, which browser are you using? I'm on Firefox and it works fine

**Comment by jimcullenaus** [comment]
I'm in Edge (Chromium-based)

**Comment by cpiber** [comment]
Problem was that Chromium deprioritizes Extension stylesheets, so the overridden property was ignored, fixed in next version
